"""agt serve — local gRPC/REST serving of AlphaGenome predictions."""

from __future__ import annotations

import argparse

from alphagenome_pytorch.cli._deps import require_extra


def register(subparsers: argparse._SubParsersAction) -> None:
    """Register the ``serve`` subcommand.

    Argument definitions live here (rather than in the serving extension) so
    that ``agt --help`` does not need to import grpc/pyfaidx/alphagenome.
    """
    p = subparsers.add_parser(
        "serve",
        help="Serve AlphaGenome predictions/scoring locally over gRPC and/or REST",
        description=(
            "Serve AlphaGenome predictions/scoring locally over gRPC and "
            "optional REST."
        ),
    )

    p.add_argument("--weights", required=True,
                   help="Path to AlphaGenome PyTorch weights file.")
    p.add_argument("--fasta", required=True,
                   help="Path to reference FASTA file.")
    p.add_argument("--gtf", default=None,
                   help="Optional GTF/Parquet annotations path.")
    p.add_argument("--polya", default=None,
                   help="Optional polyA annotations path.")
    p.add_argument("--track-metadata", default=None,
                   help="Optional parquet metadata file generated by extract_track_metadata.py.")
    p.add_argument("--device", default="cpu",
                   help="Torch device (e.g., cpu, cuda:0).")
    p.add_argument("--host", default="127.0.0.1",
                   help="Bind host for serving endpoints.")

    p.add_argument("--grpc-port", type=int, default=50051,
                   help="gRPC server port.")
    p.add_argument("--disable-grpc", action="store_true",
                   help="Disable gRPC server.")

    p.add_argument("--rest-port", type=int, default=None,
                   help="REST server port (disabled when not provided).")
    p.add_argument("--log-level", default="INFO",
                   choices=["DEBUG", "INFO", "WARNING", "ERROR"],
                   help="Logging level.")


def run(args: argparse.Namespace) -> int:
    """Run the ``serve`` command."""
    require_extra("serving", "serve")

    from alphagenome_pytorch.extensions.serving.cli import run as run_server

    return run_server(args)
